### ISSUE TITLE
Take Survey page doesn't show the logged in user

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/navbar#18]
When I go to Take Survey page the navbar shows "Log in" instead of the logged in user.

**Comment by stevenolen** [comment]
There should only be a few specific instances where this could happen.  For example -- when i visit the page while logged in I see the logged in user's username without issue.  Could I have a step-by-step to reproduce?

**Comment by ctrance** [comment]
@stevenolen - Please follow the steps below:
- clear cache
- from the dashboard click "survey taking"
- log in
- after logging in and redirected to "survey taking page" the nav bar still shows 'log in' instead of the user's username

Note: I was using FF 39 on Windows 7.

**Comment by stevenolen** [comment]
@ctrance this should be fixed now, thanks for the detail report :+1:

**Comment by ctrance** [comment]
@stevenolen I still don't see my username after logging in and redirected to taking surveys page. I already cleared cache and re-open the browser...
![capture](https://cloud.githubusercontent.com/assets/1034174/9043073/c55f8022-39c7-11e5-90ba-20b4938cb0f8.PNG)

**Comment by stevenolen** [comment]
@ctrance sorry about that, **now** it should be fixed :)

**Comment by ctrance** [comment]
fixed
